import { useEffect } from 'react';

import { Card, CardContent, CardHeader, CardTitle, FormSelect } from '@lunejs/ui';

import { CustomFieldType } from '@/lib/api/types';
import { getCustomFieldTypeData } from '@/lib/custom-fields/utils/custom-field.utils';

import { useCustomObjectFormContext } from '../use-form/use-form';

export const CustomObjectConfigurationCard = () => {
  const form = useCustomObjectFormContext();

  const fields = form.watch('fields');

  const availableForDisplay = fields.filter(
    field => field.type === CustomFieldType.SingleLineText && !!field.name
  );

  useEffect(() => {
    if (!availableForDisplay.length) form.setValue('displayField', 'auto');
  }, [fields]);

  return (
    <Card>
      <CardHeader className="flex">
        <CardTitle>Configuration</CardTitle>
      </CardHeader>
      <CardContent className="flex gap-4 items-end">
        <FormSelect
          control={form.control}
          name="displayField"
          label="Display field"
          description="Field used as the title and slug for each entry"
          items={[
            { label: 'Autogenerated', value: 'auto' },
            ...availableForDisplay.map(field => {
              return {
                label: field.name,
                value: field.name,
                icon: getCustomFieldTypeData(field.type).icon
              };
            })
          ]}
        />
      </CardContent>
    </Card>
  );
};
