services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: vendyx_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - '6500:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d vendyx_test']
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  postgres_data:
