services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: vendyx_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - '6500:5432'
    tmpfs:
      - /var/lib/postgresql/data

volumes:
  postgres_data:
